version: '2.1'

executors:
  terraform:
    - image: naiama/longor:0.1.0
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD

jobs:
  deploy:
    executor: terraform
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            echo "region = \"$aws_region\"" >> config.aws.backend
            echo "access_key = \"$aws_access_key\"" >> config.aws.backend
            echo "secret_key = \"$aws_secret_key\"" >> config.aws.backend
      - run:
          command: |
            terraform init -reconfigure -backend-config=config.aws.backend
      - run:
          command: |
            terraform fmt
      - run:
          command: |
            terraform validate
      - run:
          command: |
            terraform plan -out=tfplan
      - run:
          command: |
            terraform apply -auto-approve tfplan

  destroy:
    executor: terraform
    resource_class: medium

workflows:
  deploy:
    jobs:
      - deploy:
          branches:
            only: main
          context:
            - terraform
            - n3-zeus
      - destroy:
          branches:
            only: sleep
          context:
            - terraform
            - n3-zeus
