version: '2.1'

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: "1.2"
      - run:
          command: |
            echo 'aws_region = "$aws_region"' >> config.aws.backend
            echo 'aws_access_key_id = "$aws_access_key"' >> config.aws.backend
            echo 'aws_secret_access_key = "$aws_secret_key"' >> config.aws.backend
            echo 'gcp_credentials = "$gcp_credentials"' >> secret.tfvars
            echo 'gcp_region = "$gcp_region"' >> secret.tfvars
            echo 'gcp_zone = "$gcp_zone"' >> secret.tfvars
      - terraform/init:
          backend_config_file: config.aws.backend
      - terraform/fmt
      - terraform/validate
      - terraform/plan:
          backend_config_file: config.aws.backend
          var_file: secret.tfvars
      - terraform/apply:
          backend_config_file: config.aws.backend
          var_file: secret.tfvars

workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle:
          context:
            - terraform
            - n3-zeus
