version: '2.1'

jobs:
  deploy:
    docker:
      - image: naiama/longor:0.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    environment:
      TF_gcp_credentials = "$gcp_credentials"
      TF_gcp_region = "$gcp_region"
      TF_gcp_zone = "$gcp_zone"
    steps:
      - checkout
      - run:
          command: |
            echo "region = \"$aws_region\"" >> config.aws.backend
            echo "access_key = \"$aws_access_key\"" >> config.aws.backend
            echo "secret_key = \"$aws_secret_key\"" >> config.aws.backend
      - run:
          command: |
            terraform init -reconfigure -backend-config=config.aws.backend
      - run:
          command: |
            terraform fmt
      - run:
          command: |
            terraform validate
      - run:
          command: |
            terraform plan -backend-config=config.aws.backend
      - run:
          command: |
            terraform apply -backend-config=config.aws.backend

workflows:
  deploy:
    jobs:
      - deploy:
          context:
            - terraform
            - n3-zeus
