version: '2.1'

parameters:
  deploy:
    default: false
    type: boolean
  destroy:
    default: false
    type: boolean

executors:
  terraform:
    working_directory: ~/project
    docker:
      - image: naiama/longor:0.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  config:
    executor: terraform
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            echo "region = \"$aws_region\"" >> config.aws.tfbackend
            echo "access_key = \"$aws_access_key\"" >> config.aws.tfbackend
            echo "secret_key = \"$aws_secret_key\"" >> config.aws.tfbackend
      - persist_to_workspace:
          root: ~/
          paths: 
            - "project"

  deploy:
    executor: terraform
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            terraform init -reconfigure -backend-config=config.aws.tfbackend
      - run:
          command: |
            terraform fmt
      - run:
          command: |
            terraform validate
      - run:
          command: |
            terraform plan -out=tfplan
      - run:
          command: |
            terraform apply -auto-approve tfplan

  destroy:
    executor: terraform
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run:
          command: |
            terraform destroy

workflows:
  deploy:
    when: << pipeline.parameters.deploy >>
    triggers:
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only: main
    jobs:
      - config:
          context:
            - n3-zeus
      - deploy:
          requires: 
            - config
          context:
            - n3-zeus
  destroy:
    when: << pipeline.parameters.destroy >>
    triggers:
      - schedule:
          cron: "0 21 * * *"
          filters:
            branches:
              only: main
    jobs:
      - config:
          context:
            - n3-zeus
      - destroy:
          requires:
            - config
          context:
            - n3-zeus
