version: '2.1'

jobs:
  deploy:
    docker:
      - image: naiama/longor:0.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            echo 'aws_region = "$aws_region"' >> config.aws.backend
            echo 'aws_access_key_id = "$aws_access_key"' >> config.aws.backend
            echo 'aws_secret_access_key = "$aws_secret_key"' >> config.aws.backend
            echo 'gcp_credentials = "$gcp_credentials"' >> secret.tfvars
            echo 'gcp_region = "$gcp_region"' >> secret.tfvars
            echo 'gcp_zone = "$gcp_zone"' >> secret.tfvars
      - run:
          command: |
            terraform init -reconfigure -backend-config=config.aws.backend
      - run:
          command: |
            terraform fmt
      - run:
          command: |
            terraform validate
      - run:
          command: |
            terraform plan -backend-config=config.aws.backend -var-file=secret.tfvars
      - run:
          command: |
            terraform apply -backend-config=config.aws.backend -var-file=secret.tfvars

workflows:
  deploy:
    jobs:
      - deploy:
          context:
            - terraform
            - n3-zeus
