version: '2.1'

executors:
  terraform:
    docker:
      - image: naiama/longor:0.1.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

jobs:
  config:
    executor: terraform
    resource_class: medium
    steps:
      - checkout
      - run:
          command: |
            echo "region = \"$aws_region\"" >> config.aws.tfbackend
            echo "access_key = \"$aws_access_key\"" >> config.aws.tfbackend
            echo "secret_key = \"$aws_secret_key\"" >> config.aws.tfbackend
      - persist_to_workspace:
          root: .

  deploy:
    executor: terraform
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            terraform init -reconfigure -backend-config=config.aws.tfbackend
      - run:
          command: |
            terraform fmt
      - run:
          command: |
            terraform validate
      - run:
          command: |
            terraform plan -out=tfplan
      - run:
          command: |
            terraform apply -auto-approve tfplan

  destroy:
    executor: terraform
    resource_class: medium
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            terraform destroy

workflows:
  deploy:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only: main
    jobs:
      - config:
          context:
            - terraform
      - deploy:
          context:
            - n3-zeus
  destroy:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only: sleep
    jobs:
      - config:
          context:
            - terraform
      - destroy:
          context:
            - n3-zeus
