#!/bin/bash

export scriptdir="$(pwd)/$(dirname "$0")"

terraform init -reconfigure -backend-config=${scriptdir}/../config.aws.tfbackend && \
terraform fmt && \
terraform validate && \
terraform plan -var-file="${scriptdir}/../secret.tfvars" -out=tfplan && \
terraform apply tfplan && \
rm tfplan
